### ISSUE TITLE
Enhance new names view

### ISSUE THREAD

**Issue by luisbosch** [ekumenlabs/webogram#11]
* More contrast to the blurred name 
* Make name appear on picture hover too
* Fix overflow of names that destroys the grid (Fix for OCDs)

**Comment by german-e-mas** [comment]
Suggestion: We can add a transparent black background to the text to enhance contrast.

![screenshot from 2018-02-22 11-43-01](https://user-images.githubusercontent.com/14120807/36544635-b393dfd0-17c5-11e8-9fe4-76273d7243bb.png)

Here, the `p` element has
```
font-weight: bold;
background: rgba(0, 0, 0, 0.5);
color: white
```

**Comment by basicNew** [comment]
misa like it ^

**Comment by tulku** [comment]
Mmm, I'm smelling a new inmedia maintainer?

**Comment by luisbosch** [comment]
I like it too,and we can get rid of the animation :)

**Comment by JessicaJackson** [comment]
+1
