### ISSUE TITLE
Improve incoming message notification

### ISSUE THREAD

**Issue by JessicaJackson** [ekumenlabs/webogram#14]
It is very hard to distinguish between general chatter and direct messages or items one is tagged. Is there a way to update the tab icon for the latter?

**Comment by tulku** [comment]
If you mute the group, then you only get notifications on direct messages, tagged messages or replies to your messages, even if those things happen in a muted group.

**Comment by JessicaJackson** [comment]
Oooh, nice! Thanks!

**Comment by luisbosch** [comment]
That was easy.
